tst

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,37 +1,61 @@
-name: Check Latest Commit on Feature Branch
+# name: Check LaTest Commit on Feature Branch
+
+# on:
+#   pull_request:
+#     branches:
+#       - main
+
+# jobs:
+#   check-laTest-commit:
+#     runs-on: ubuntu-laTest
+
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v2
+
+#     - name: Get feature branch name
+#       run: |
+#         Test="${{ github.event.pull_request.head.ref }}"
+#         MAIN_BRANCH="${{ github.event.pull_request.base.ref }}"
+#         # echo "Test=$Test" >> $GITHUB_ENV
+#         # echo "MAIN_BRANCH=$MAIN_BRANCH" >> $GITHUB_ENV
+
+#     - name: Get laTest commit on feature branch
+#       run: |
+#         LATEST_COMMIT=$(git log --pretty=format:"%H" -n 1 "$Test")
+#         # echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV
+#         echo "LaTest commit on the feature branch: $LATEST_COMMIT"
+
+#     - name: Check for Test files in the laTest commit
+#       run: |
+#         CHANGED_FILES=$(git diff --name-only $LATEST_COMMIT^ $LATEST_COMMIT)
+        
+#         if echo "$CHANGED_FILES" | grep -E '.*Test\.java$' &>/dev/null; then
+#           echo "Test files found in the laTest commit."
+#         else
+#           echo "No Test files found in the laTest commit. Please add Tests."
+#         fi
+
+name: Check Unit Tests in Pull Request
 
 on:
   pull_request:
-    branches:
-      - main
+    types:
+      - opened
+      - synchronize
 
 jobs:
-  check-latest-commit:
+  check_unit_tests:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Get feature branch name
+    - name: Check for unit tests in PR
       run: |
-        test="${{ github.event.pull_request.head.ref }}"
-        MAIN_BRANCH="${{ github.event.pull_request.base.ref }}"
-        # echo "test=$test" >> $GITHUB_ENV
-        # echo "MAIN_BRANCH=$MAIN_BRANCH" >> $GITHUB_ENV
-
-    - name: Get latest commit on feature branch
-      run: |
-        LATEST_COMMIT=$(git log --pretty=format:"%H" -n 1 "$test")
-        # echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV
-        echo "Latest commit on the feature branch: $LATEST_COMMIT"
-
-    - name: Check for test files in the latest commit
-      run: |
-        CHANGED_FILES=$(git diff --name-only $LATEST_COMMIT^ $LATEST_COMMIT)
-        
-        if echo "$CHANGED_FILES" | grep -E '.*Test\.java$' &>/dev/null; then
-          echo "Test files found in the latest commit."
-        else
-          echo "No test files found in the latest commit. Please add tests."
+        test_results=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "tests/")
+        if [ -z "$test_results" ]; then
+          echo "Error: Unit tests are missing in the pull request."
+          exit 1
         fi
